use_frameworks!

platform :ios, '10.0'

target 'YYHUD_Example' do
  pod 'YYHUD', :path => '../'

  target 'YYHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
